### ISSUE TITLE
Use gcc -m32 and ld -m elf_i386

### ISSUE THREAD

**Issue by cirosantilli** [programble/bare-metal-tetris#1]
Wouldn't it be more user friendly / likely to work out of the box if the default were to use those options instead of a custom named cross compiler name `i386-elf-gcc`, as in https://github.com/cirosantilli/bare-metal-tetris/blob/37a8f8e89a3129067825ab2aa14faa1eb33b5e62/Makefile#L2 ?

That just works on Ubuntu.

Thanks for this great example.

**Comment by causal-agent** [comment]
I changed the defaults to be more cross-platform, which I guess means it doesn't work on any platforms rather than only some, in this case. Technically, one should always use a cross-compiler for this sort of thing.

By the way, [Tetrasm](https://github.com/programble/tetrasm) is a much better implementation of Tetris.

**Comment by cirosantilli** [comment]
Feel free to close if you think it's best as currently.

I recommend putting a deprecation note on the GitHub description of this repo and README if Tetrasm superseeds it, and linking to it.

I found this repo through GitHub searches like "bare metal hello world", so I would add "bare metal" to that repo's description as well: that is the main interest I suppose.

Why did you port C to NASM? :-)

**Comment by causal-agent** [comment]
Will do. I just wanted to learn x86 ASM for some reason, basically.
